name: Publish Retype powered website to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish to retype branch

    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v2

      # Set up .NET SDK (install the required 7.0.410 version)
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.410'

      # Install Retype tool globally using dotnet
      - name: Install Retype globally
        run: dotnet tool install --global retypeapp --version 3.6.0

      # Add .NET tools to the PATH for future steps
      - name: Add .NET tools to PATH
        run: echo "/home/runner/.dotnet/tools" >> $GITHUB_PATH

      # Build the site using Retype (this uses retypeapp)
      - uses: retypeapp/action-build@latest
   

        

      # Publish the site to GitHub Pages
      - uses: retypeapp/action-github-pages@latest
        with:
          update-branch: true
